image: quay.io/python-devs/ci-image

stages:
  - test
  - codecov
  - deploy

qa:
  script:
    - tox -e qa

tests:
  script:
    - tox -e py27,py35,py36,py37,py38

coverage:
  script:
    - tox -e py27-cov,py35-cov,py36-cov
  artifacts:
    paths:
      - coverage.xml

diffcov:
  script:
    - tox -e py27-diffcov,py35-diffcov,py36-diffcov

docs:
  script:
    - tox -e docs

codecov:
  stage: codecov
  dependencies:
    - coverage
  script:
    - codecov --token $CODECOV_TOKEN
  when: on_success

release:
  stage: deploy
  only:
    - /^v\d+\.\d+(\.\d+)?([abc]\d*)?$/
  script:
    - tox -e release
